service: graphql-lambda

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2 # sydney

functions:
  graphql:
    handler: handler.server
    events:
      - http:
          path: /
          method: post
          cors: true

  playground:
    handler: handler.playground
    events:
      - http:
          path: /
          method: get
          cors: true
